# Generated by Django 4.2.7 on 2025-11-25 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("extract_proforma", "Extract Proforma Data"),
                            ("generate_po", "Generate Purchase Order"),
                            ("validate_receipt", "Validate Receipt"),
                            ("extract_text", "Extract Text from Document"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_file",
                    models.FileField(
                        blank=True, null=True, upload_to="ai_processing/inputs/"
                    ),
                ),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="ai_processing/outputs/"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Time in seconds", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_jobs",
                        to="purchases.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_processing_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedDocumentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("proforma", "Proforma Invoice"),
                            ("purchase_order", "Purchase Order"),
                            ("receipt", "Receipt"),
                            ("invoice", "Invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("vendor_address", models.TextField(blank=True)),
                ("vendor_email", models.EmailField(blank=True, max_length=254)),
                ("vendor_phone", models.CharField(blank=True, max_length=20)),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("payment_terms", models.CharField(blank=True, max_length=200)),
                ("delivery_terms", models.CharField(blank=True, max_length=200)),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="AI confidence (0-1)", null=True
                    ),
                ),
                (
                    "extraction_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_data",
                        to="documents.aiprocessingjob",
                    ),
                ),
            ],
            options={
                "db_table": "extracted_document_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                            ("requires_review", "Requires Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(help_text="Overall validation score (0-1)"),
                ),
                ("vendor_match", models.BooleanField(default=False)),
                ("amount_match", models.BooleanField(default=False)),
                ("items_match", models.BooleanField(default=False)),
                ("date_valid", models.BooleanField(default=False)),
                ("discrepancies", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_result",
                        to="documents.aiprocessingjob",
                    ),
                ),
                (
                    "reference_po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_results",
                        to="purchases.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "document_validation_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("invoice", "Invoice"),
                            ("receipt", "Receipt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "template_content",
                    models.TextField(help_text="HTML template with placeholders"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_templates",
                "ordering": ["name"],
            },
        ),
    ]
