# Generated by Django 4.2.7 on 2025-11-25 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_level",
                    models.IntegerField(help_text="Approval level (1, 2, etc.)"),
                ),
                ("approved", models.BooleanField(default=True)),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Approval/rejection comments"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "approvals",
                "ordering": ["approval_level", "approved_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the purchase request", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of items/services needed"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount in USD",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "proforma",
                    models.FileField(
                        blank=True,
                        help_text="Proforma invoice or quotation",
                        null=True,
                        upload_to="proformas/",
                    ),
                ),
                (
                    "purchase_order",
                    models.FileField(
                        blank=True,
                        help_text="Generated purchase order",
                        null=True,
                        upload_to="purchase_orders/",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        help_text="Purchase receipt for validation",
                        null=True,
                        upload_to="receipts/",
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Vendor/supplier name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "vendor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Vendor contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        blank=True, help_text="Expected delivery date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proforma_processed", models.BooleanField(default=False)),
                ("po_generated", models.BooleanField(default=False)),
                ("receipt_validated", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approved_requests",
                        through="purchases.Approval",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the request",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Request",
                "verbose_name_plural": "Purchase Requests",
                "db_table": "purchase_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("specifications", models.TextField(blank=True)),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "request_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("proforma_extract", "Proforma Extraction"),
                            ("po_generation", "PO Generation"),
                            ("receipt_validation", "Receipt Validation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="processing", max_length=20)),
                ("input_file", models.CharField(blank=True, max_length=500)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Time in seconds", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="purchases.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "document_processing_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="approval",
            name="purchase_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="purchases.purchaserequest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approval",
            unique_together={("purchase_request", "approval_level")},
        ),
    ]
